apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: seatunnel-master-config
    files:
      - hazelcast.yaml
      - hazelcast-client.yaml
      - seatunnel.yaml
  - name: seatunnel-log4j-config
    files:
      - log4j.properties
