log4j.rootLogger=DEBUG, STDOUT, FILE

log4j.appender.STDOUT=org.apache.log4j.ConsoleAppender
log4j.appender.STDOUT.target=System.out
log4j.appender.STDOUT.layout=org.apache.log4j.PatternLayout
log4j.appender.STDOUT.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%-30.30c{1}] [%t] - %m%n

log4j.appender.FILE=org.apache.log4j.RollingFileAppender
log4j.appender.FILE.File=/tmp/seatunnel.log
log4j.appender.FILE.MaxFileSize=100MB
log4j.appender.FILE.MaxBackupIndex=3
log4j.appender.FILE.layout=org.apache.log4j.PatternLayout
log4j.appender.FILE.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%-30.30c{1}] [%t] - %m%n

log4j.logger.org.apache.seatunnel.api.table.factory.FactoryUtil=WARN
log4j.logger.org.apache.seatunnel.engine.server.telemetry.log.TaskLogManagerService=WARN
