apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/seatunnel-worker

patches:
  - path: patch-deployment.yaml

configMapGenerator:
  - name: seatunnel-worker-config
    behavior: replace
    files:
      - hazelcast.yaml
      - seatunnel.yaml
  - name: seatunnel-log4j-config
    behavior: replace
    files:
      - log4j.properties      